//*****************************************************************************
//*****************************************************************************
//  FILENAME:  AMUX0.h
//  Version: 1.4, Updated on 2006/04/24 at 14:54:57
//  Generated by PSoC Designer ver 4.4  b1884 : 14 Jan, 2007
//
//  DESCRIPTION:  AMux4 User Module C Language interface file for the
//                22/24/25/26/27xxx PSoC family of devices.
//
//-----------------------------------------------------------------------------
//      Copyright (c) Cypress MicroSystems 2000-2003. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************


#include <m8c.h>
//-------------------------------------------------
// Defines for AMUX0 API's.
//-------------------------------------------------
#define AMUX0_PORT0_0                  0x00
#define AMUX0_PORT0_2                  0x01
#define AMUX0_PORT0_4                  0x02
#define AMUX0_PORT0_6                  0x03

#define AMUX0_PORT0_1                  0x00
#define AMUX0_PORT0_3                  0x01
#define AMUX0_PORT0_5                  0x02
#define AMUX0_PORT0_7                  0x03


#pragma fastcall16 AMUX0_InputSelect
#pragma fastcall16 AMUX0_Start
#pragma fastcall16 AMUX0_Stop

//-------------------------------------------------
// Prototypes of the AMUX0 API.
//-------------------------------------------------

extern void AMUX0_InputSelect(BYTE bChannel);
extern void AMUX0_Start(void);
extern void AMUX0_Stop(void);

// end of file AMUX0.h
