PROJNAME=psocusb
DEVICE=CY8C24794
BASEDEVICE=CY8C24090
PROJPATH=C:/work/project/psocusb
PSOCDIR=C:/PROGRA~2/CYPRES~1/PSOCDE~1
INCLUDE_PATH=C:/PROGRA~2/CYPRES~1/PSOCDE~1/tools/include/CY8C24~2
CSRCS= ctype.c main.c pr.c sht11.c
LIBCSRCS=
ASMSRCS=
LIBASMSRCS= adcinc_1.asm adcinc_1int.asm amux0.asm e2prom_1.asm pga_1.asm psocconfig.asm psocconfigtbl.asm timer8_1.asm timer8_1int.asm usbuart_1.asm usbuart_1_cls_cdc.asm usbuart_1_descr.asm usbuart_1_drv.asm usbuart_1_std.asm usbuart_1int.asm
OBJECT_SOURCES= ctype.c main.c pr.c sht11.c
FILLVALUE=0x30
LASTROM=0x3fff
LASTRAM=0x3ff
LAST_DATARAM=0x2ff
CODECOMPRESSOR=
MORE_CFLAGS=-Wf-Osize -Wf-LMM4 -D_LMM
RELSTART=0x1a0
CDEFINES=
LIBS=
LIB_PATH=
ENABLE_ALIGN_SHIFT=0
LMM=1
SYS_INC_CONTENTS:=SYSTEM_STACK_PAGE:_equ_3 SYSTEM_STACK_BASE_ADDR:_equ_0h SYSTEM_LARGE_MEMORY_MODEL:_equ_1 SYSTEM_SMALL_MEMORY_MODEL:_equ_0 
SYSTEM_TOOLS=1
CSFLOW=
CONFIG_NAMES=psocusb 
